# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [ ]:
import numpy as np

2. Create a null vector of size 10 

In [1]:
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [7]:
import numpy as np
vector = np.arange(10,49)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


4. Find the shape of previous array in question 3

In [9]:
import numpy as np
l=[10, 11, 12 ,13, 14, 15, 16, 17, 18 ,19, 20, 21, 22 ,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48]
x=np.array(l)
np.reshape

<function numpy.reshape(a, newshape, order='C')>

5. Print the type of the previous array in question 3

In [10]:
import numpy as np
x.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [1]:
import numpy as np
print(np.__version__)
print(np.show_config())


1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/test/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/test/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/test/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/test/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/test/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/test/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/test/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/test/anaconda3\\Library\\include']
None


7. Print the dimension of the array in question 3


In [12]:
import numpy as np
a = np.array([10, 11, 12 ,13, 14, 15, 16, 17, 18 ,19, 20, 21, 22 ,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48])
print(a)
np.ndim(a)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


1

8. Create a boolean array with all the True values

In [30]:
import numpy as np
l=[10, 11, 12 ,13, 14, 15, 16, 17, 18 ,19, 20, 21, 22 ,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48]
x=np.array(l)
x>9

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

9. Create a two dimensional array




In [18]:
import numpy as np
x=np.zeros((10,10))
x.shape

(10, 10)

10. Create a three dimensional array



In [29]:
import numpy as np
z=x.reshape(2,2,25)
print(z)


[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0.]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [33]:
import numpy as np
vector = (49,10)
print(vector)

[]


12. Create a null vector of size 10 but the fifth value which is 1 

In [34]:
import numpy as np
x = np.zeros(10)
print(x)
x[4] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [36]:
import numpy as np
array_2D=np.identity(3)
print(array_2D)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [38]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5]) 
arr = arr.astype('float64') 
print(arr) 
print(arr.dtype)

[1. 2. 3. 4. 5.]
float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [40]:
arr1 = np.array([[1., 2., 3.],
            [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],
           [7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [43]:
arr1 = np.array([[1., 2., 3.],
            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.], 
            [7., 2., 12.]])

comparison = arr1 == arr2
equal_arrays = comparison.all() 
  
print(equal_arrays)  


False


17. Extract all odd numbers from arr with values(0-9)

In [46]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
a[a % 2 == 1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [50]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
-a[a % 2 == 1]

array([-1, -3, -5, -7, -9])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [12]:
import numpy as np
arr=np.arange(10)
arr[5] 
arr[5:9] 
arr[5:9] = 12
print(arr)

[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [60]:
import numpy as np
x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [65]:
arr2d = np.array([[1, 2, 3],
            [4, 5, 6], 

            [7, 8, 9]])
arr2d[5] = 12
print(arr2d)


IndexError: index 5 is out of bounds for axis 0 with size 3

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [5]:
import numpy as np
arr3d = np.array([[[1, 2, 3], 
                   [4, 5, 6]], 
                  [[7, 8, 9], 
                   [10, 11, 12]]])
arr3d = arr.astype('float64') 
print(arr3d) 


NameError: name 'arr' is not defined

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [6]:
x=[[0,1,2,3,4],[5,6,7,8,9]]
d=np.array(x)
np.split(d,[5])

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([], shape=(0, 5), dtype=int32)]

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [7]:
x=np.arange(0,9)


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

[ 0  1  2  3  4 12 12 12  8  9]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [67]:
import numpy as np
x = np.random.random((10,10))
xmin, xmax = x.min(), x.max()
print(xmin, xmax)

0.005155818583539973 0.9917067156814561


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [69]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [34]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print(data)
data[names == 'Will'] 

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 0.11991198  0.3171614   0.85769826 -0.49020848]
 [ 1.54341411 -1.53681532 -1.09428271 -0.44780118]
 [ 1.17922654  0.74784416  0.88382515  0.56445244]
 [-1.16283322 -1.04339096 -0.24293854  1.94256264]
 [-1.2629728  -0.42424112 -0.15490427 -0.64774994]
 [-0.18244709 -0.89480514  0.71534695 -2.92348796]
 [-1.25078801 -0.27795303 -1.36594826  0.36021415]]


array([[ 1.17922654,  0.74784416,  0.88382515,  0.56445244],
       [-1.2629728 , -0.42424112, -0.15490427, -0.64774994]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [24]:
import numpy as np
arr = np.arange(0,15)
x = arr.reshape((5,3))
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [20]:
import numpy as np
arr = np.arange(0,16)
x = arr.reshape((2,2,4))
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


33. Swap axes of the array you created in Question 32

In [23]:
import numpy as np
arr = np.arange(0,16)
x = arr.reshape((2,2,4))
arr = x.swapaxes(1, 2)
print(arr)

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [27]:
import numpy as np
arr = np.arange(10)
print(arr)
z = np.sqrt(arr ** 2)
print(z)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [9]:
h=np.random.rand(12)
print(h)
k=np.random.rand(12)
print(k)
hmax, kmax = h.max(), k.max()
print(hmax, kmax)


[0.9516956  0.95495524 0.79255066 0.23222572 0.16669565 0.08383243
 0.10135986 0.51747691 0.18580207 0.17403364 0.3663472  0.01285222]
[0.95450404 0.20821407 0.20836694 0.53016837 0.30295009 0.73330748
 0.27089634 0.08492013 0.93350052 0.95502729 0.10588101 0.36148613]
0.9549552372145863 0.9550272930620497


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [73]:
names=np.unique(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [10]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
result = np.setdiff1d(a, b)
print(result)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [13]:
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
del ['numpy.array'(2,6)]
newColumn = numpy.array([[10,10,10]])


SyntaxError: cannot delete function call (<ipython-input-13-cdaeb12b661c>, line 2)

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [72]:
x = np.array([1,2,3],[4,5,6])
y = np.array([[6,23],[-1,7],[8,9]])

z = x * y
print(z)

TypeError: Field elements must be 2- or 3-tuples, got '4'

40. Generate a matrix of 20 random values and find its cumulative sum

In [64]:
import numpy as np
c=np.random.rand(2,3,4)
np.cumsum(c)
c

array([[[0.25513263, 0.87233409, 0.78330841, 0.518371  ],
        [0.70058222, 0.08073483, 0.53882208, 0.39773141],
        [0.04228533, 0.2548556 , 0.10920496, 0.56562016]],

       [[0.12935992, 0.99445676, 0.07894568, 0.00847845],
        [0.22101259, 0.46104586, 0.32305064, 0.41205198],
        [0.64222519, 0.14845323, 0.41713948, 0.13767406]]])